# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2026-03-26T12:56:05+00:00

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, RootModel


class AudioType(Enum):
    DEFAULT = 'DEFAULT'
    NOTIFICATION = 'NOTIFICATION'
    ALARM = 'ALARM'


class MinuteSettings(BaseModel):
    sound_file_name: str = Field(
        ..., description='サウンドファイル名', title='sound_file_name'
    )
    sound_types: list[AudioType] | None = Field(
        None, description='再生対象の音声タイプ一覧', min_length=1, title='sound_types'
    )


class DailyScheduleItem(BaseModel):
    hour: float = Field(..., description='時間 (0-23)', title='hour')
    minutes: list[float] | None = Field(
        None, description='分 (0-59)', max_length=60, min_length=0, title='minutes'
    )
    minute_settings: dict[str, MinuteSettings] | None = Field(
        None, description='分ごとの詳細設定', title='minute_settings'
    )


class DailySchedule(RootModel[list[DailyScheduleItem]]):
    root: list[DailyScheduleItem] = Field(
        ...,
        description='時間毎の設定',
        max_length=24,
        min_length=0,
        title='hour_settings',
    )


class WeeklySchedule(BaseModel):
    model_config = ConfigDict(
        extra='forbid',
    )
    holiday: DailySchedule | None = None
    monday: DailySchedule
    tuesday: DailySchedule
    wednesday: DailySchedule
    thursday: DailySchedule
    friday: DailySchedule
    saturday: DailySchedule
    sunday: DailySchedule
