# generated by datamodel-codegen:
#   filename:  schema.json
#   timestamp: 2025-12-16T23:53:39+00:00

from __future__ import annotations

from typing import List

from pydantic import BaseModel, Field, RootModel


class WeeklyScheduleItem(BaseModel):
    hour: float = Field(..., description='時間 (0-23)', title='hour')


class WeeklySchedule(RootModel[List[List[WeeklyScheduleItem]]]):
    root: List[List[WeeklyScheduleItem]] = Field(
        ..., description='各曜日の時間設定', title='weekly_schedule'
    )
